import '../styles/global.scss';
import Header from '@/components/layout/Header/header';
import Footer from '@/components/layout/Footer/footer';
import { ComponentsWrapper } from '../context/stepsComponents';
import { FormBuildDataWrapper } from "@/context/formBuildData";
import FloatingIcons from '@/components/FloatingIcons/floatingIcons';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <FloatingIcons />
        <Header/>
            <ComponentsWrapper>
              <FormBuildDataWrapper>
                {children}
              </FormBuildDataWrapper>
            </ComponentsWrapper>
        <Footer/>
      </body>
    </html>
  )
}
